# Generated by Django 4.0.3 on 2022-03-31 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_store_app', '0002_alter_customer_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='delivery_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping_store_app.address'),
        ),
    ]
