# Generated by Django 4.0.3 on 2022-03-31 11:24

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_store_app', '0003_alter_customer_delivery_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'DELIVERY ADDRESS'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'CREDIT CARDS'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='cc_number',
            field=creditcards.models.CardNumberField(max_length=16, verbose_name='card number'),
        ),
    ]
